{application,oam_db,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{oam_db_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[oam_db,oam_db_app,oam_db_lib,oam_db_sup]},
              {licenses,["Apache 2.0"]},
              {links,[]}]}.
